#!/bin/sh
# A simple bash script that uses Applescript to
# open multiple files in Preview. For example:
# "preview hello.png world.gif *.jpg"

# echo $*

if [ -z "$*" ]; then
  echo "Usage: $0 [FILE(S)]"
  exit
fi

PWD=${PWD}
for file in $*;
do
  if [ -n "$FILES" ]
  then
    FILES="$FILES, \"$file\""
  else
    FILES="\"$file\""
  fi
done;
osascript<<EOF
tell application "Preview"
  activate
  open {$FILES}
end tell
EOF